# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

S_eigen <- function(X) {
    .Call('_HiDimCI_S_eigen', PACKAGE = 'HiDimCI', X)
}

bootstrapCpp <- function(X, B, dt, verbose) {
    .Call('_HiDimCI_bootstrapCpp', PACKAGE = 'HiDimCI', X, B, dt, verbose)
}

S <- function(X, Y) {
    .Call('_HiDimCI_S', PACKAGE = 'HiDimCI', X, Y)
}

johansenCpp <- function(X, r, A, B, Psi, dt = 1) {
    .Call('_HiDimCI_johansenCpp', PACKAGE = 'HiDimCI', X, r, A, B, Psi, dt)
}

sampleVAR1 <- function(N, X0, A, mu, D, e, dt) {
    .Call('_HiDimCI_sampleVAR1', PACKAGE = 'HiDimCI', N, X0, A, mu, D, e, dt)
}

test_vecm <- function(X, r, A, B, dt) {
    .Call('_HiDimCI_test_vecm', PACKAGE = 'HiDimCI', X, r, A, B, dt)
}

